### ISSUE TITLE
Testar uso de autenticação do DJango

### ISSUE THREAD

**Issue by ArthurJahn** [parlametria/leggo-backend#383]
Estudo dos scripts de limpeza e carregamento dos dados de proposições para possibilitar a implementação da autenticação de usuários.

**Comment by andersonms1** [comment]
Mapeamento inicial do update das proposições

`leggo-backend/api/management/commands/update_data.py`
![image](https://user-images.githubusercontent.com/17951542/154598368-c038bb13-f907-4d0f-95b8-c5232b3b18cf.png)
`leggo-backend/api/management/commands/clear_and_import.py`
![image](https://user-images.githubusercontent.com/17951542/154598293-e10998a1-c46b-4d7c-8f37-52e6b57e42dc.png)

**Comment by ArthurJahn** [comment]
@andersonms1 tem um comando do manage.py `clear_tables` que pode ter a ver com esse processo também. Acho que vale dar uma olhada

**Comment by andersonms1** [comment]
## Proposta para implementação de login

Ainda não entendi toda a relação de Proposição com os outros modelos e antes de continuar na tentativa de fazer um mapeamento extenso uma ideia de como podemos implementar a funcionalidade de login na atual arquitetura. 

[O Django possuí um 'despachador' ](https://docs.djangoproject.com/en/4.0/topics/signals/) capaz de executar [uma ação caso um model seja criado por exemplo](https://stackoverflow.com/questions/10672572/django-how-can-i-tell-if-the-post-save-signal-triggers-on-a-new-object), assim ao criar uma tabela do tipo `Proposição` ou `<AnyModel>Proposição` o 'despachador' pode executar uma função que preenche um campo da tabela com a tabela de usuários interessados. 

![Untitled Diagram-Sequence drawio (1)](https://user-images.githubusercontent.com/17951542/155393328-113b0c5b-35cc-4da7-98b8-43a37a0879aa.png)

A função `update_reference()` então procura nas models de `usuários interessados` a atual `Preposição` e o update da referência.
 
![Untitled Diagram-Page-1 drawio](https://user-images.githubusercontent.com/17951542/155393705-723a4296-ac85-4b1d-a364-5d4e226d2351.png)

**Comment by ArthurJahn** [comment]
@andersonms1 Acho que podemos testar essa solução na próxima sprint. Só vamos precisar ficar de olho nesses processos no futuro porque em algum momento as proposições vão parar de ser carregadas por meio de arquivos CSV e vão começar a ser cadastradas via painel, pelo usuário autenticado.

Acredito que o processo executado atualmente em produção, utiliza os mesmos scripts de homologação também.

Sobre o uso dos signals, acredito que essa alternativa vai ser boa pra essa primeira versão. Quando repensarmos o carregamento das proposições pra evitar que sejam recriadas no banco a gente repensa esse fluxo. O que acha?

**Comment by andersonms1** [comment]
Entendido, dependendo no futuro a gente pode padronizar o login mesmo. 

Acho que eu posso ter me expressado mal ali mesmo, os scripts para homologação e os scripts do make file são coisas diferentes e acho que referenciei como a mesma coisa.
